Repository QuEraComputing/bloqade-circuit, pull requests merged in 2025-10, with the labels that each got.

#519 Add more detailed AssertionError for non GridQubits in conflict graph…
  src/bloqade/cirq_utils/noise/model.py
Labels: backport

#512 Refactor & simplify noise dialect
  src/bloqade/cirq_utils/emit/noise.py
  src/bloqade/pyqrack/squin/noise/native.py
  src/bloqade/squin/__init__.py
  src/bloqade/squin/analysis/nsites/impls.py
  src/bloqade/squin/noise/__init__.py
  src/bloqade/squin/noise/_dialect.py
  src/bloqade/squin/noise/_interface.py
  src/bloqade/squin/noise/_wrapper.py
  src/bloqade/squin/noise/stmts.py
  src/bloqade/squin/stdlib/broadcast/__init__.py
  src/bloqade/squin/stdlib/broadcast/clifford.py
  src/bloqade/squin/stdlib/broadcast/noise.py
  src/bloqade/squin/stdlib/channel.py
  src/bloqade/squin/stdlib/simple/__init__.py
  src/bloqade/squin/stdlib/simple/clifford.py
  src/bloqade/squin/stdlib/simple/noise.py
  test/cirq_utils/cirq_to_squin.py
  test/cirq_utils/noise/noise_models.py
  test/cirq_utils/noise/noisy_ghz.py
  test/cirq_utils/noise/one_zone_correlated_noise.py
  test/cirq_utils/squin_noise_to_cirq.py
  test/cirq_utils/test_squin_noise_to_cirq.py
  test/pyqrack/squin/test_noise.py
  test/squin/analysis/test_nsites_analysis.py
  test/squin/clifford/test_stdlib_clifford.py
  test/squin/noise/test_stdlib_noise.py
  test/squin/test_stdlib_shorthands.py
  test/squin/test_stochastic_unitary.py
  test/stim/passes/squin_meas_to_stim.py
  test/stim/passes/squin_noise_to_stim.py
  test/stim/passes/squin_qubit_to_stim.py
  test/stim/passes/squin_wire_to_stim.py
Labels: breaking, rfc

#520 Refactor cirq - squin emit and lowering
  src/bloqade/cirq_utils/emit/__init__.py
  src/bloqade/cirq_utils/emit/base.py
  src/bloqade/cirq_utils/emit/clifford.py
  src/bloqade/cirq_utils/emit/noise.py
  src/bloqade/cirq_utils/emit/qubit.py
  src/bloqade/cirq_utils/lowering.py
  test/cirq_utils/noise/test_noise_models.py
  test/cirq_utils/noise/test_noisy_ghz.py
  test/cirq_utils/noise/test_one_zone_correlated_noise.py
  test/cirq_utils/test_cirq_to_squin.py
  test/cirq_utils/test_clifford_to_cirq.py
  test/cirq_utils/test_squin_noise_to_cirq.py
  test/cirq_utils/test_squin_to_cirq.py
Labels: breaking
