Repository QuEraComputing/bloqade-circuit, pull requests merged in 2025-07, with the labels that each got.

#340 adding Wired statement for regionalized wire semantics
  src/bloqade/squin/rewrite/canonicalize.py
  src/bloqade/squin/wire.py
  test/squin/rewrite/test_canonicalize.py
  test/squin/wire/__init__.py
  test/squin/wire/test_check.py
Labels: rfc

#377 Fix warning about invalid escape sequence
  src/bloqade/squin/op/stmts.py
Labels: documentation, squin

#386 U3 to Clifford Z rotation alternatives
  src/bloqade/squin/rewrite/U3_to_clifford.py
  test/squin/rewrite/test_U3_to_clifford.py
Labels: bug, backport 0.5

#369 Add heuristic noise model in cirq
  src/bloqade/cirq_utils/__init__.py
  src/bloqade/cirq_utils/noise/__init__.py
  src/bloqade/cirq_utils/noise/_two_zone_utils.py
  src/bloqade/cirq_utils/noise/conflict_graph.py
  src/bloqade/cirq_utils/noise/model.py
  src/bloqade/cirq_utils/noise/transform.py
  src/bloqade/cirq_utils/parallelize.py
  src/bloqade/squin/cirq/lowering.py
  test/cirq_utils/noise/test_noise_models.py
  test/cirq_utils/noise/test_noisy_ghz.py
  test/cirq_utils/noise/test_one_zone_correlated_noise.py
  test/cirq_utils/test_transpile.py
  test/squin/cirq/test_cirq_to_squin.py
Labels: backport 0.5

#413 add ability to track number of measurements at statements of interest
  src/bloqade/analysis/measure_id/analysis.py
  src/bloqade/analysis/measure_id/impls.py
  test/analysis/measure_id/test_measure_id.py
Labels: backport 0.6

#415 Implement stdlib shorthands for direct application of squin gates
  src/bloqade/squin/__init__.py
  src/bloqade/squin/gate.py
  src/bloqade/squin/parallel.py
  test/squin/test_stdlib_shorthands.py
Labels: backport 0.6
