Repository QuEraComputing/bloqade-circuit, pull requests merged in 2025-05, with the labels that each got.

#224 Change Clifford String to Pauli String
  src/bloqade/squin/op/stmts.py
Labels: squin

#240 simplify loads
  src/bloqade/qasm2/__init__.py
  src/bloqade/qasm2/_qasm_loading.py
Labels: qasm2, lowering

#237 Fixing extraction of global qubit ids
  src/bloqade/qasm2/passes/noise.py
  src/bloqade/qasm2/rewrite/heuristic_noise.py
  test/qasm2/passes/test_heuristic_noise.py
Labels: bug

#250 Restrict qasm2 parser so it rejects multiple expressions in if body
  src/bloqade/qasm2/parse/qasm2.lark
  test/qasm2/parse/invalid_programs/invalid_if.qasm
  test/qasm2/parse/programs/main.qasm
  test/qasm2/parse/programs/valid_if.qasm
  test/qasm2/parse/test_roundtrip.py
Labels: breaking

#279 Clean up import path
  src/bloqade/qasm2/dialects/core/__init__.py
  src/bloqade/qasm2/dialects/expr/__init__.py
  src/bloqade/qasm2/dialects/uop/__init__.py
  src/bloqade/qasm2/dialects/uop/schedule.py
  src/bloqade/qasm2/rewrite/desugar.py
  src/bloqade/squin/noise/__init__.py
  src/bloqade/squin/noise/_wrapper.py
  src/bloqade/squin/op/__init__.py
  src/bloqade/squin/op/_wrapper.py
  src/bloqade/squin/op/stdlib.py
  src/bloqade/squin/rewrite/stim_rewrite_util.py
  src/bloqade/stim/__init__.py
  src/bloqade/stim/dialects/__init__.py
  src/bloqade/stim/dialects/auxiliary/__init__.py
  src/bloqade/stim/dialects/auxiliary/emit.py
  src/bloqade/stim/dialects/collapse/__init__.py
  src/bloqade/stim/dialects/collapse/emit_str.py
  src/bloqade/stim/dialects/gate/__init__.py
  src/bloqade/stim/dialects/gate/emit.py
  src/bloqade/stim/dialects/noise/emit.py
  src/bloqade/stim/emit/__init__.py
  src/bloqade/stim/emit/stim_str.py
  test/stim/dialects/stim/emit/test_stim_ctrl.py
  test/stim/dialects/stim/emit/test_stim_detector.py
  test/stim/dialects/stim/emit/test_stim_meas.py
  test/stim/dialects/stim/emit/test_stim_noise.py
  test/stim/dialects/stim/emit/test_stim_obs_inc.py
  test/stim/dialects/stim/emit/test_stim_ppmeas.py
  test/stim/dialects/stim/emit/test_stim_spp.py
  test/stim/dialects/stim/test_stim_const.py
  test/stim/wrapper/test_wrapper.py
Labels: breaking
