Repository QuEraComputing/bloqade-circuit, pull requests merged in 2025-04, with the labels that each got.

#11 Squin Operator Sites Analysis
  src/bloqade/squin/analysis/nsites/__init__.py
  src/bloqade/squin/analysis/nsites/analysis.py
  src/bloqade/squin/analysis/nsites/impls.py
  src/bloqade/squin/analysis/nsites/lattice.py
  src/bloqade/squin/op/stmts.py
  src/bloqade/squin/op/traits.py
  test/squin/analysis/test_nsites_analysis.py
Labels: enhancement, squin, priority: high

#9 upgrading from 0.14 -> 0.16
  pyproject.toml
  src/bloqade/noise/native/stmts.py
  src/bloqade/pyqrack/noise/native.py
  src/bloqade/qasm2/dialects/core/__init__.py
  src/bloqade/qasm2/dialects/core/_emit.py
  src/bloqade/qasm2/dialects/core/_typeinfer.py
  src/bloqade/qasm2/dialects/core/stmts.py
  src/bloqade/qasm2/dialects/expr/__init__.py
  src/bloqade/qasm2/dialects/expr/_emit.py
  src/bloqade/qasm2/dialects/expr/_from_python.py
  src/bloqade/qasm2/dialects/expr/_interp.py
  src/bloqade/qasm2/dialects/expr/stmts.py
  src/bloqade/qasm2/dialects/glob.py
  src/bloqade/qasm2/dialects/indexing.py
  src/bloqade/qasm2/dialects/inline.py
  src/bloqade/qasm2/dialects/noise.py
  src/bloqade/qasm2/dialects/parallel.py
  src/bloqade/qasm2/dialects/uop/__init__.py
  src/bloqade/qasm2/dialects/uop/_emit.py
  src/bloqade/qasm2/dialects/uop/stmts.py
  src/bloqade/qasm2/groups.py
  src/bloqade/qasm2/parse/lowering.py
  src/bloqade/qasm2/passes/py2qasm.py
  src/bloqade/qasm2/passes/qasm2py.py
  src/bloqade/qbraid/lowering.py
  src/bloqade/squin/op/stmts.py
  src/bloqade/squin/qubit.py
  src/bloqade/squin/wire.py
  src/bloqade/stim/dialects/aux/lowering.py
  src/bloqade/stim/dialects/aux/stmts/annotate.py
  src/bloqade/stim/dialects/aux/stmts/const.py
  src/bloqade/stim/dialects/collapse/stmts/measure.py
  src/bloqade/stim/dialects/collapse/stmts/pp_measure.py
  src/bloqade/stim/dialects/collapse/stmts/reset.py
  src/bloqade/stim/dialects/gate/stmts/base.py
  src/bloqade/stim/dialects/gate/stmts/pp.py
  src/bloqade/stim/dialects/noise/stmts.py
  test/pyqrack/test_target.py
  test/qasm2/passes/test_heuristic_noise.py
  test/qasm2/test_inline.py
  test/qasm2/test_lowering.py
Labels: priority: high

#208 Add pyqrack extas with platform dependent constraints.
  pyproject.toml
Labels: enhancement, rfc
