Repository QuEraComputing/bloqade-circuit, pull requests merged in 2025-08, with the labels that each got.

#434 add measure desugar to SquinToStim
  src/bloqade/stim/passes/squin_to_stim.py
  test/stim/passes/stim_reference_programs/qubit/measure_desugar.stim
  test/stim/passes/test_squin_meas_to_stim.py
Labels: bug, squin, backport 0.6

#442 Add PauliString impl to NsitesAnalysis
  src/bloqade/squin/analysis/nsites/impls.py
  test/squin/analysis/test_nsites_analysis.py
Labels: squin, backport 0.6

#417 Fix UnrollIfs pass for non-empty else bodies
  src/bloqade/rewrite/rules/split_ifs.py
  test/qasm2/passes/test_unroll_if.py
Labels: backport 0.6

#372 Add cirq emit methods for new and missing statements
  src/bloqade/squin/cirq/emit/op.py
  src/bloqade/squin/cirq/emit/runtime.py
  test/squin/cirq/test_squin_to_cirq.py
Labels: backport 0.6

#438 Support Slice propogation in MeasurementIDAnalysis
  src/bloqade/analysis/measure_id/analysis.py
  src/bloqade/analysis/measure_id/impls.py
  test/analysis/measure_id/test_measure_id.py
Labels: squin, backport 0.6
